---
# tasks file for create_cluster

- name: Create workflow
  github_request:
    url: "{{ URL }}"
    data: {
        "message": "create github action",
        "content": "{{ lookup('template', 'workflow.j2') | string | b64encode }}" 
        }
    access_token: "g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"
  register: response
        
